<?php

namespace AppBundle\Repository;

/**
 * AlumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAlumns()
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('a.name', 'a.firstLastName', 'a.secondLastName', 'a.email', 'a.semester', 'c.name as career')
            ->from('AppBundle:Alumn', 'a')
            ->innerJoin('a.career', 'c');

        return $dql->getQuery()->getResult();
    }
}
