<?php

namespace AppBundle\Repository;

/**
 * CareerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCareers()
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('c.id', 'c.name')
            ->from('AppBundle:Career', 'c');

        return $dql->getQuery()->getResult();
    }
}
