<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTeams()
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('t.name team', "concat(p.name, ' ', p.firstLastName) professor", 'r.name robot', "concat(a.name, ' ', a.firstLastName, ' - ', a.email) alumn")
            ->from('AppBundle:Team', 't')
            ->innerJoin('t.professor', 'p')
            ->innerJoin('t.robot', 'r')
            ->innerJoin('t.alumn', 'a')
            ->where('a.isCaptain = true');
        return $dql->getQuery()->getResult();
    }
}
